spring.application.name=tbs-transportOperationSystems-BE

spring.datasource.url=jdbc:postgresql://tmsx3em.tema-systems.com:49370/postgres
spring.datasource.username=postgres
spring.datasource.password=Tiger123
spring.datasource.driver-class-name=org.postgresql.Driver




# =========================
# SQL Server (Secondary DB)
# =========================
sqlserver.datasource.url=jdbc:sqlserver://tmsx3em.tema-systems.com:49360;databaseName=tbs;encrypt=true;trustServerCertificate=true
sqlserver.datasource.username=SA
sqlserver.datasource.password=Tiger123
sqlserver.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl





spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
transport.path=/api/v1
transport.secret.key=TransportManagement
db.schema=tms

intacct.senderId=tema-systemsMPP
intacct.senderPassword=*Sachin@1411
intacct.companyId=tema-systemsMPP-DEV
intacct.userId=emma
intacct.userPassword=*Nani@1411!

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.default_schema=tms

server.port=8082
#server.ssl.enabled=true
#server.ssl.key-store=classpath:ssl/tms-local.p12
#server.ssl.key-store-password=Nani@123
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tms-local
