USE [tbs]
GO

-- ============================================================
-- XX10CPLANCHA — TMS Planning Trip Header
-- Written when a trip is LOCKED from TMS
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10CPLANCHA' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10CPLANCHA] (
        XNUMPC_0        NVARCHAR(30)    NOT NULL PRIMARY KEY,  -- Trip code e.g. VR-KCC01-20260624-001
        XFCY_0          NVARCHAR(10)    NULL,                  -- Site/facility
        XDATE_0         DATE            NULL,                  -- Plan date
        XVEHCODE_0      NVARCHAR(20)    NULL,                  -- Vehicle code
        XDRIVERID_0     NVARCHAR(50)    NULL,                  -- Driver ID
        XSTARTTIME_0    NVARCHAR(10)    NULL,                  -- Start time HH:MM
        XENDTIME_0      NVARCHAR(10)    NULL,                  -- End time HH:MM
        XTOTDIST_0      NVARCHAR(20)    NULL,                  -- Total distance
        XTOTIME_0       NVARCHAR(10)    NULL,                  -- Travel time HH:MM
        XDROPS_0        INT             NULL,                  -- Number of drops
        XPICKUPS_0      INT             NULL,                  -- Number of pickups
        XSTOPS_0        INT             NULL,                  -- Total stops
        XNOPACK_0       INT             NULL,                  -- Number of packages
        XTOTWEIGHT_0    NVARCHAR(20)    NULL,                  -- Total weight
        XTOTVOL_0       NVARCHAR(20)    NULL,                  -- Total volume
        XCAPACITY_0     NVARCHAR(20)    NULL,                  -- Vehicle capacity
        XOPTISTATUS_0   NVARCHAR(20)    NULL,                  -- Optimisation status
        XDEPSIT_0       NVARCHAR(10)    NULL,                  -- Departure site
        XARRSIT_0       NVARCHAR(10)    NULL,                  -- Arrival site
        XGENBY_0        NVARCHAR(20)    NULL,                  -- Generated by
        XUSRCODE_0      NVARCHAR(50)    NULL,                  -- User code
        XCREDAT_0       DATETIME        NULL                   -- Created timestamp
    )
END
GO

-- ============================================================
-- XX10CPLANCHD — TMS Planning Trip Detail (per stop)
-- One row per stop per trip
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10CPLANCHD' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10CPLANCHD] (
        ID              INT             IDENTITY(1,1) PRIMARY KEY,
        XNUMPC_0        NVARCHAR(30)    NOT NULL,              -- Trip code (FK to XX10CPLANCHA)
        SDHNUM_0        NVARCHAR(30)    NULL,                  -- Document number (delivery/pickup)
        XSEQ_0          INT             NULL,                  -- Sequence in trip
        XTYPE_0         NVARCHAR(10)    NULL,                  -- DROP | PICKUP
        XBPCODE_0       NVARCHAR(20)    NULL,                  -- Customer code
        XADRESCODE_0    NVARCHAR(20)    NULL,                  -- Address code
        XCITY_0         NVARCHAR(50)    NULL,                  -- City
        XARRDATE_0      NVARCHAR(10)    NULL,                  -- Arrival date YYYY-MM-DD
        XARRTIME_0      NVARCHAR(10)    NULL,                  -- Arrival time HH:MM
        XDEPDATE_0      NVARCHAR(10)    NULL,                  -- Departure date
        XDEPTIME_0      NVARCHAR(10)    NULL,                  -- Departure time HH:MM
        XSRVTIME_0      NVARCHAR(10)    NULL,                  -- Service time HH:MM
        XWAITTIME_0     NVARCHAR(10)    NULL,                  -- Waiting time HH:MM
        XDISTFRMPREV_0  NVARCHAR(20)    NULL,                  -- Distance from prev stop
        XTRVTIMEFRMPREV_0 NVARCHAR(10)  NULL,                  -- Travel time from prev
        XNETWEIGHT_0    FLOAT           NULL,                  -- Net weight
        XVOLUME_0       FLOAT           NULL,                  -- Volume
        XUSRCODE_0      NVARCHAR(50)    NULL,                  -- User code
        XCREDAT_0       DATETIME        NULL                   -- Created timestamp
    )
    CREATE INDEX IDX_PLANCHD_NUMPC ON [TMSNEW].[XX10CPLANCHD] (XNUMPC_0)
    CREATE INDEX IDX_PLANCHD_DOC   ON [TMSNEW].[XX10CPLANCHD] (SDHNUM_0)
END
GO

-- ============================================================
-- XX10CLODSTOH — Load Vehicle Stock Header (LVS)
-- Written when a trip is VALIDATED from TMS
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10CLODSTOH' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10CLODSTOH] (
        ID              INT             IDENTITY(1,1) PRIMARY KEY,
        XVRSEL_0        NVARCHAR(30)    NOT NULL UNIQUE,       -- Trip code
        XFCY_0          NVARCHAR(10)    NULL,                  -- Site
        XDATE_0         DATE            NULL,                  -- Date
        XVEHCODE_0      NVARCHAR(20)    NULL,                  -- Vehicle
        XDRIVERID_0     NVARCHAR(50)    NULL,                  -- Driver
        XSTARTTIME_0    NVARCHAR(10)    NULL,                  -- Start time
        XENDTIME_0      NVARCHAR(10)    NULL,                  -- End time
        XTOTDIST_0      NVARCHAR(20)    NULL,                  -- Total distance
        XDROPS_0        INT             NULL,                  -- Drops count
        XPICKUPS_0      INT             NULL,                  -- Pickups count
        XNOPACK_0       INT             NULL,                  -- Packages
        XTOTWEIGHT_0    NVARCHAR(20)    NULL,                  -- Total weight
        XTOTVOL_0       NVARCHAR(20)    NULL,                  -- Total volume
        XLOADFLG_0      INT             NULL DEFAULT 1,        -- 1=Generated,2=...,5=Completed,11=Cancelled
        XDEPSIT_0       NVARCHAR(10)    NULL,                  -- Departure site
        XARRSIT_0       NVARCHAR(10)    NULL,                  -- Arrival site
        XUSRCODE_0      NVARCHAR(50)    NULL,                  -- User code
        XCREDAT_0       DATETIME        NULL                   -- Created timestamp
    )
    CREATE INDEX IDX_LODSTOH_VR ON [TMSNEW].[XX10CLODSTOH] (XVRSEL_0)
END
GO
