USE [tbs]
GO

-- ============================================================
-- XX10CPLANCHA — TMS Planning Trip Header
-- Written when a trip is LOCKED from TMS
-- Column names match CBTTL reference system exactly
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10CPLANCHA' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10CPLANCHA] (
        XNUMPC_0        NVARCHAR(30)    NOT NULL PRIMARY KEY,  -- Trip code e.g. VR-KCC01-20260624-001
        XFCY_0          NVARCHAR(10)    NULL,                  -- Site/facility (departure)
        XDATLIV_0       DATE            NULL,                  -- Plan/delivery date
        XVEHCODE_0      NVARCHAR(20)    NULL,                  -- Vehicle code
        XDRIVERID_0     NVARCHAR(50)    NULL,                  -- Driver ID
        XDESFCY_0       NVARCHAR(10)    NULL,                  -- Destination/arrival site
        XHEUDEP_0       NVARCHAR(10)    NULL,                  -- Scheduled departure time HH:MM
        XHEUARR_0       NVARCHAR(10)    NULL,                  -- Scheduled return time HH:MM
        XHEUEXEC_0      NVARCHAR(10)    NULL,                  -- Execution time HH:MM (when locked)
        XTOTDIST_0      NVARCHAR(20)    NULL,                  -- Total distance
        XTOTTIME_0      NVARCHAR(10)    NULL,                  -- Total time HH:MM
        XTRVTIME_0      NVARCHAR(10)    NULL,                  -- Travel time HH:MM
        XSRVTIME_0      NVARCHAR(10)    NULL,                  -- Service time HH:MM
        XDROPS_0        INT             NULL,                  -- Number of drops
        XPICKUPS_0      INT             NULL,                  -- Number of pickups
        XSTOPS_0        INT             NULL,                  -- Total stops (drops+pickups)
        XNOPACK_0       INT             NULL,                  -- Number of packages
        XTOTWEIGHT_0    NVARCHAR(20)    NULL,                  -- Total weight
        XTOTVOL_0       NVARCHAR(20)    NULL,                  -- Total volume
        XCAPACITY_0     NVARCHAR(20)    NULL,                  -- Vehicle capacity
        XOPTISTATUS_0   NVARCHAR(20)    NULL,                  -- Optimisation status
        XDEPSIT_0       NVARCHAR(10)    NULL,                  -- Departure site
        XARRSIT_0       NVARCHAR(10)    NULL,                  -- Arrival site
        XGENBY_0        NVARCHAR(20)    NULL,                  -- Generated by (PLANNER/AUTO)
        XUSRCODE_0      NVARCHAR(50)    NULL,                  -- User code
        XCREDATTIM_0    DATETIME        NULL                   -- Created timestamp
    )
    CREATE INDEX IDX_PLANCHA_FCY  ON [TMSNEW].[XX10CPLANCHA] (XFCY_0)
    CREATE INDEX IDX_PLANCHA_DATE ON [TMSNEW].[XX10CPLANCHA] (XDATLIV_0)
    CREATE INDEX IDX_PLANCHA_VEH  ON [TMSNEW].[XX10CPLANCHA] (XVEHCODE_0)
END
GO

-- ============================================================
-- XX10CPLANCHD — TMS Planning Trip Detail (per stop)
-- One row per delivery/pickup stop per trip
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10CPLANCHD' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10CPLANCHD] (
        ID                  INT             IDENTITY(1,1) PRIMARY KEY,
        XNUMPC_0            NVARCHAR(30)    NOT NULL,              -- Trip code (FK → XX10CPLANCHA)
        SDHNUM_0            NVARCHAR(30)    NULL,                  -- Delivery/pickup document number
        XSEQ_0              INT             NULL,                  -- Stop sequence number
        XTYPE_0             NVARCHAR(10)    NULL,                  -- DROP | PICKUP
        XBPCODE_0           NVARCHAR(20)    NULL,                  -- Customer/BP code
        XADRESCODE_0        NVARCHAR(20)    NULL,                  -- Address code
        XCITY_0             NVARCHAR(50)    NULL,                  -- City
        XARRDATE_0          NVARCHAR(10)    NULL,                  -- Arrival date YYYY-MM-DD
        XARRTIME_0          NVARCHAR(10)    NULL,                  -- Arrival time HH:MM
        XDEPDATE_0          NVARCHAR(10)    NULL,                  -- Departure date YYYY-MM-DD
        XDEPTIME_0          NVARCHAR(10)    NULL,                  -- Departure time HH:MM
        XSRVTIME_0          NVARCHAR(10)    NULL,                  -- Service time at stop HH:MM
        XWAITTIME_0         NVARCHAR(10)    NULL,                  -- Waiting time HH:MM
        XDISTFRMPREV_0      NVARCHAR(20)    NULL,                  -- Distance from previous stop (km)
        XTRVTIMEFRMPREV_0   NVARCHAR(10)    NULL,                  -- Travel time from previous stop HH:MM
        XNETWEIGHT_0        FLOAT           NULL,                  -- Net weight of this stop
        XVOLUME_0           FLOAT           NULL,                  -- Volume of this stop
        XUSRCODE_0          NVARCHAR(50)    NULL,                  -- User code
        XCREDATTIM_0        DATETIME        NULL                   -- Created timestamp
    )
    CREATE INDEX IDX_PLANCHD_NUMPC ON [TMSNEW].[XX10CPLANCHD] (XNUMPC_0)
    CREATE INDEX IDX_PLANCHD_DOC   ON [TMSNEW].[XX10CPLANCHD] (SDHNUM_0)
END
GO

-- ============================================================
-- XX10CLODSTOH — Load Vehicle Stock Header (LVS)
-- Written when a trip is VALIDATED from TMS
-- XLOADFLG_0 values: 1=Generated, 2=In Progress, 5=Completed, 11=Cancelled
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10CLODSTOH' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10CLODSTOH] (
        ID              INT             IDENTITY(1,1) PRIMARY KEY,
        XVRSEL_0        NVARCHAR(30)    NOT NULL UNIQUE,       -- Trip/VR code (links to XX10CPLANCHA)
        XFCY_0          NVARCHAR(10)    NULL,                  -- Site/facility
        XDATLIV_0       DATE            NULL,                  -- Delivery date
        XVEHCODE_0      NVARCHAR(20)    NULL,                  -- Vehicle code
        XDRIVERID_0     NVARCHAR(50)    NULL,                  -- Driver ID
        XHEUDEP_0       NVARCHAR(10)    NULL,                  -- Departure time HH:MM
        XHEUARR_0       NVARCHAR(10)    NULL,                  -- Return time HH:MM
        XTOTDIST_0      NVARCHAR(20)    NULL,                  -- Total distance
        XTOTTIME_0      NVARCHAR(10)    NULL,                  -- Total time
        XTRVTIME_0      NVARCHAR(10)    NULL,                  -- Travel time
        XDROPS_0        INT             NULL,                  -- Drops count
        XPICKUPS_0      INT             NULL,                  -- Pickups count
        XNOPACK_0       INT             NULL,                  -- Packages count
        XTOTWEIGHT_0    NVARCHAR(20)    NULL,                  -- Total weight
        XTOTVOL_0       NVARCHAR(20)    NULL,                  -- Total volume
        XLOADFLG_0      INT             NULL DEFAULT 1,        -- Load flag: 1=Generated
        XDEPSIT_0       NVARCHAR(10)    NULL,                  -- Departure site
        XARRSIT_0       NVARCHAR(10)    NULL,                  -- Arrival site
        XUSRCODE_0      NVARCHAR(50)    NULL,                  -- User code
        XCREDATTIM_0    DATETIME        NULL                   -- Created timestamp
    )
    CREATE INDEX IDX_LODSTOH_VR   ON [TMSNEW].[XX10CLODSTOH] (XVRSEL_0)
    CREATE INDEX IDX_LODSTOH_FCY  ON [TMSNEW].[XX10CLODSTOH] (XFCY_0)
    CREATE INDEX IDX_LODSTOH_DATE ON [TMSNEW].[XX10CLODSTOH] (XDATLIV_0)
    CREATE INDEX IDX_LODSTOH_FLAG ON [TMSNEW].[XX10CLODSTOH] (XLOADFLG_0)
END
GO

-- ============================================================
-- XX10TRIPS — TMS Trip master table
-- Written when a trip is CONFIRMED from TMS
-- Used by XTMSDLVY_TMS + XTMSPICK_TMS views for route status
-- ============================================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name='XX10TRIPS' AND schema_id=SCHEMA_ID('TMSNEW'))
BEGIN
    CREATE TABLE [TMSNEW].[XX10TRIPS] (
        TRIPCODE        NVARCHAR(30)    NOT NULL PRIMARY KEY,  -- Trip code e.g. VR-KCC01-20260624-001
        optistatus      NVARCHAR(20)    NULL DEFAULT 'Open',   -- Open | Optimized | Locked
        lock            INT             NULL DEFAULT 0,        -- 0=unlocked 1=locked
        FCY_0           NVARCHAR(10)    NULL,                  -- Site/facility
        DATLIV_0        DATE            NULL,                  -- Plan/delivery date
        VEHCODE         NVARCHAR(20)    NULL,                  -- Vehicle code
        DRIVERID        NVARCHAR(50)    NULL                   -- Driver ID
    )
    CREATE INDEX IDX_XX10TRIPS_FCY  ON [TMSNEW].[XX10TRIPS] (FCY_0)
    CREATE INDEX IDX_XX10TRIPS_DATE ON [TMSNEW].[XX10TRIPS] (DATLIV_0)
    CREATE INDEX IDX_XX10TRIPS_LOCK ON [TMSNEW].[XX10TRIPS] (lock)
END
GO
