package com.transport.tms.Fleet.Dto;

import lombok.Data;

import java.util.Date;
import java.util.List;
import java.util.UUID;

@Data
public class FleetDriverVO {
    private Integer updTick;
    private String driverId;
    private String driver;
    private Boolean active;
    private String bptnum;
    private String lanmain;
    private String lansec;
    private String cry;
    private Date bir;
    private Date credattim;
    private Date upddattim;
    private UUID auuid;
    private String creusr;
    private String updusr;
    private String bpaaddlig0;
    private String bpaaddlig1;
    private String bpaaddlig2;
    private String poscod;
    private String cty;
    private String mob;
    private String web;
    private String licenum;
    private Date licedat;
    private Short licetyp;
    private Date validat;
    private String delivby;
    private Date lastvime;
    private String fcy;
    private String sat;
    private String tel0;
    private String tel1;
    private String tel2;
    private String tel3;
    private String tel4;
    private String xuser;
    private String xpwd;
    private String xpwd1;
    private Boolean xsigcon;
    private Boolean xcamcon;
    private Boolean xper;
    private Integer xlgnflg;
    private String xbus;
    private String xloginseqno;
    private String xbadnum;
    private Date xadrdat;
    private String xdocno;
    private String xx10cGeox;
    private String xx10cGeoy;
    private String xlncstarttim;
    private String xlncdur;
    private String styzon;
    private Boolean xpaycon;
    private String xuvycod;
    private Boolean xskpcon;
    private Boolean xrescon;
    private Boolean xqtychgcon;
    private Boolean xspotcon;
    private Boolean xpickupcon;
    private Boolean xsihcon;
    private Short xlogflag;
    private String xmacadd;
    private Boolean xdeposit;
    private Boolean xgeocon;
    private Integer xnooftrips;
    private Boolean xsalesrep;
    private Boolean xdriver;
    private Boolean xdsd;
    private Boolean xsalrout;
    private int xcondriv;
    private int x1cunion;
    private Boolean x10cmon;
    private Boolean x10ctues;
    private Boolean x10cwed;
    private Boolean x10cthu;
    private Boolean x10cfri;
    private Boolean x10csat;
    private Boolean x10csun;
    private Integer x1coverhrs;
    private Integer xmaxhrsday;
    private Integer xmaxhrsweek;
    private Integer xdriverhrs;
    private Boolean xallvehicle;
    private Date xuvystrdat;
    private Date xuvyenddat;
    private Boolean xlonghaul;
    private String note;
    private int x10csup;
    private int x10csupflg;
    private List<Document> documentList;
    private List<VehicleTable> siteList;
    private List<VehicleTable> vehicleClassList;
    private List<UnavailableDays> unavailableDaysList;
    private byte[] image;
}
